    - name: Forwarding Masquerade and Restart Services
      shell: |
        echo "net.ipv4.ip_forward=1" | tee -a /etc/sysctl.conf 
        sysctl -p
        iptables -t nat -A POSTROUTING -o enp3s0 -j MASQUERADE
        mkdir -p /etc/iptables
        iptables-save > /etc/iptables/rules.v4
        netplan apply

    - name: Copy rc.local
      copy:
        src: rc.local
        dest: /etc/rc.local
        owner: root
        group: root
        mode: '0755'

    - name: Prepare user-data and umount /mnt
      shell: |
        export SBC_ROOT_HASH_PASSWORD=$(openssl passwd -6 -salt $(tr -dc A-Za-z0-9 </dev/urandom | head -c 8) nucPassw0rd)
        sed -i "s#THE_PASSWORD#$SBC_ROOT_HASH_PASSWORD#g" /var/www/html/efiboot/cloud-init/user-data
        echo "Unmounting /mnt"
        umount /mnt

